### ISSUE TITLE
clockwork 2.0.1 breaks clockwork-test

### ISSUE THREAD

**Issue by somethingnew2-0** [kevin-j-m/clockwork-test#12]
I believe [this commit](https://github.com/Rykian/clockwork/commit/0c62018f8773854a68832d96b76bbdf37381160e#diff-4a9dab64377cf0b9a2ce870638eac345) broke the wrapping logic for the Clockwork::Test::Manager class

**Comment by kevin-j-m** [comment]
Thanks for the report and for doing some initial investigation. 

I think step one may be to get something like [Appraisal](https://github.com/thoughtbot/appraisal) running so we can test against multiple versions, now that there's active development on clockwork again.

I'm not sure when I'll be able to devote time to addressing 2.0.1 compatibility, but hopefully I can get that test matrix up and running this week. As always, PRs are welcome.

**Comment by kevin-j-m** [comment]
I have a local branch set up that introduces Appraisal; however, the nature of the incompatibility seems to cause the test process to simply hang. As a result, I'm not going to push or PR that until I've fixed the issue, as the test suite would never finish on CI.

**Comment by somethingnew2-0** [comment]
That's the behavior I noticed as well. The test process just hangs.

**Comment by kevin-j-m** [comment]
@somethingnew2-0 do you have a project using clockwork that's on > 2.0.1, or that you'd like to upgrade? Would you like to look @ #13 and reference that branch in your Gemfile to test against your project as another data point for me?

**Comment by somethingnew2-0** [comment]
Yep, that fixes!

When I specify your branch in my Gemfile
`gem 'clockwork-test',  :git => 'https://github.com/kevin-j-m/clockwork-test.git', :branch => '201-compatibility'`
and then `bundle update clockwork` the tests pass again!

Thanks for such a fast fix!

**Comment by kevin-j-m** [comment]
Released [0.2.0](https://rubygems.org/gems/clockwork-test/versions/0.2.0) so this should be available to update from Rubygems. Thanks again for reporting @somethingnew2-0.

**Comment by somethingnew2-0** [comment]
Thanks!
