### ISSUE TITLE
Forces `config/clock.rb`

### ISSUE THREAD

**Issue by cnemeth** [kevin-j-m/clockwork-test#23]
If location of `clock.rb` is not `config`, specs fail. Shouldn't this be more flexible? 

```
Failures:

  1) Clockwork runs the test one time
     Failure/Error: Clockwork::Test.run(max_ticks: 1)

     LoadError:
       cannot load such file -- ./config/clock.rb
     # ./spec/clock_spec.rb:7:in `block (2 levels) in <top (required)>'
```

**Comment by kevin-j-m** [comment]
If I understand your issue correctly, you should be able to resolve it by specifying the location of your clock file with the [file](https://github.com/kevin-j-m/clockwork-test#file) option to `run`. The [default](https://github.com/kevin-j-m/clockwork-test/blob/f63ce0d5368f909b1566ac9842d7c55fe0ff9ade/lib/clockwork/test.rb#L44) is `./config/clock.rb`.

**Comment by cnemeth** [comment]
sorry, my bad, shouda read the the REAME ;-)
