### ISSUE TITLE
Testing 2 clock instances

### ISSUE THREAD

**Issue by knagode** [kevin-j-m/clockwork-test#24]
I have 2 clock instances (2 clock.rb files: `clock.rb` && `clock_business_logic_xyz.rb`). Everything 
runs OK but I am not sure how to rspec test both of them. 

All tests are checking only tasks in `clock.rb` file. 

Any ideas?

**Comment by knagode** [comment]
Found it. There is file argument for handling this. Awesome!
```
Clockwork::Test.run(start_time: 18.seconds.ago, end_time: Time.now, tick_speed: 1.second, file: './config/clock_business_logic_xyz.rb')
```

**Comment by kevin-j-m** [comment]
@knagode this is the [second issue](https://github.com/kevin-j-m/clockwork-test/issues/23) asking about specifying the clock file location. Do you have a suggestion for how, or if, we should improve visibility of this option, which is currently documented in the [README](https://github.com/kevin-j-m/clockwork-test#file)?

**Comment by knagode** [comment]
Huh .. I seems like well documented method. Not sure why I didn't see it.
