### ISSUE TITLE
Wildcards for times not supported?

### ISSUE THREAD

**Issue by ce07c3** [kevin-j-m/clockwork-test#31]
```rb
EVERY_TEN_FULL_MINUTES = [
  "**:00",
  "**:10",
  "**:20",
  "**:30",
  "**:40",
  "**:50"
].freeze

every(1.hour, TestJob.name, at: EVERY_TEN_FULL_MINUTES, tz: "UTC") { }
```

```rb
# start at beginning of day to ensure we match the ten full minutes
now = Time.current.in_time_zone("UTC")
start_at = now.beginning_of_day

Clockwork::Test.run(max_ticks: 3, start_at: start_at, tick_speed: 30.minutes)

assert_equal(2, Clockwork::Test.times_run(TestJob.name))
```

```
rails test test/config/clockwork_test.rb:21
Running via Spring preloader in process 20916
Run options: --seed 52425

# Running:

F

Failure:
ClockworkTest#test_test_job [test/config/clockwork_test.rb:28]:
Expected: 2
  Actual: 0
```

**Comment by kevin-j-m** [comment]
Hi! I pushed a [branch](https://github.com/kevin-j-m/clockwork-test/compare/wildcard) validating clockwork test picking up wildcard values in the `at:` option. This spec is passing for me.

The `tick_speed` might be causing issues for you, though I'd expect that to pick up the job 3 times (at 00:00, 00:300, and 1:00, the three clock ticks you'd get), but I'm not certain/obviously that's not the case.

Perhaps you can use that test case as a guide?

**Comment by ce07c3** [comment]
Sure, I'll check it out! 👍

**Comment by ce07c3** [comment]
The commit is gone, but I can see the branch was merged and deleted. I'll check off master now.

**Comment by ce07c3** [comment]
Still having the same issues.

**Comment by kevin-j-m** [comment]
I've recreated your exact scenario in another [branch](https://github.com/kevin-j-m/clockwork-test/compare/every-10), given in rspec, not minitest.

There are two commits:

1. The [first](https://github.com/kevin-j-m/clockwork-test/commit/fbd55e0342fe6cdab47d1535a7ce8bad4a2e077c) sets the ticks and clock speed as you have it, and if verifies that the job runs on each clock tick.
2. The [second](https://github.com/kevin-j-m/clockwork-test/commit/f413cafcf09a3863b71b7f897c35d4f06672cf65) runs every minute over the course of an hour, verifying that it runs on every multiple of 10.

IMO, scenario 2 is a better representation of the scenario you're looking to validate; however either show the job running more than zero times.

Note that also in my clock file I would recommend saying this job runs every minute. While saying it runs every hour works (as evident in these tests), I think it's less clear to see a job run every 10 minutes when it's said to run hourly.

**Comment by kevin-j-m** [comment]
Note that with both scenarios I've created tracking down this issue, I cannot reproduce the issue of `Clockwork::Test` not supporting wildcard times.
